"""
Revenue Outreach Engine — sends free audit reports to real businesses,
converts them into paying customers.

Flow:
1. Audit a prospect's website
2. Generate beautiful HTML report
3. Send personalized email with results + offer to fix
4. Track responses and conversions
"""
import os
import sys
import json
import smtplib
import ssl
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)

from services.website_audit.audit_engine import run_audit, generate_html_report


def load_credentials():
    creds_path = os.path.join(BASE_DIR, "credentials.json")
    with open(creds_path) as f:
        raw = json.load(f)
    email_cfg = raw.get("email", raw)
    return {
        "email": email_cfg.get("from_email", email_cfg.get("username", email_cfg.get("email", ""))),
        "password": email_cfg.get("password", ""),
        "smtp_host": email_cfg.get("smtp_host", "smtp.gmail.com"),
        "smtp_port": int(email_cfg.get("smtp_port", 587)),
    }


def load_prospects():
    prospects_path = os.path.join(BASE_DIR, "data", "prospects.json")
    if os.path.exists(prospects_path):
        with open(prospects_path) as f:
            data = json.load(f)
        # Handle both flat list and dict-by-niche formats
        if isinstance(data, list):
            return data
        elif isinstance(data, dict):
            flat = []
            for niche, items in data.items():
                if isinstance(items, list):
                    for item in items:
                        item["niche"] = niche
                        flat.append(item)
            return flat
    return []


def save_outreach_log(log_entry):
    log_path = os.path.join(BASE_DIR, "data", "outreach_log.json")
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    logs = []
    if os.path.exists(log_path):
        with open(log_path) as f:
            logs = json.load(f)
    logs.append(log_entry)
    with open(log_path, "w") as f:
        json.dump(logs, f, indent=2)


def generate_outreach_email(prospect_name, website_url, audit_report):
    """Generate personalized cold email with free audit results."""
    score = audit_report.get("overall_score", "N/A")
    grade = audit_report.get("grade", "N/A")
    issues = audit_report.get("seo", {}).get("issues", [])
    warnings = audit_report.get("seo", {}).get("warnings", [])

    color = "#00cc66" if score >= 80 else "#ffa500" if score >= 60 else "#ff4444"

    issues_html = ""
    for issue in issues[:5]:
        issues_html += f'<li style="color:#ff6b6b;padding:4px 0">{issue}</li>'
    for warn in warnings[:3]:
        issues_html += f'<li style="color:#ffa500;padding:4px 0">{warn}</li>'

    subject = f"Your website scored {score}/100 — free audit inside"

    html = f"""
<div style="font-family:'Segoe UI',Arial,sans-serif;max-width:600px;margin:0 auto;background:#0a0a0a;color:#e0e0e0;border-radius:12px;overflow:hidden">

<div style="background:linear-gradient(90deg,#00d4ff,#7b2ff7);padding:20px 30px;text-align:center">
<h1 style="font-size:24px;font-weight:800;color:#fff;margin:0">Free Website Audit Report</h1>
</div>

<div style="padding:30px">

<p style="font-size:16px;color:#ccc;margin-bottom:20px">Hi {prospect_name},</p>

<p style="color:#aaa;line-height:1.7;margin-bottom:20px">
I ran a quick AI audit on <strong style="color:#00d4ff">{website_url}</strong> and wanted to share the results with you — completely free, no strings attached.
</p>

<div style="text-align:center;margin:30px 0">
<div style="display:inline-block;width:120px;height:120px;border-radius:50%;border:5px solid {color};text-align:center;line-height:120px">
<span style="font-size:42px;font-weight:800;color:{color}">{score}</span>
</div>
<div style="color:#888;margin-top:8px;font-size:14px">Grade: {grade}</div>
</div>

<div style="background:#111;border:1px solid #222;border-radius:10px;padding:20px;margin-bottom:25px">
<h3 style="color:#ff6b6b;margin-bottom:10px;font-size:14px">Issues Found:</h3>
<ul style="list-style:none;padding:0;margin:0">
{issues_html}
</ul>
</div>

<p style="color:#aaa;line-height:1.7;margin-bottom:20px">
These issues may be affecting your Google rankings and costing you potential customers. The good news: most of them can be fixed quickly.
</p>

<div style="text-align:center;margin:30px 0">
<a href="https://aoeua.com/order.html" style="display:inline-block;padding:14px 40px;background:linear-gradient(90deg,#00d4ff,#7b2ff7);color:#fff;text-decoration:none;border-radius:50px;font-weight:700;font-size:16px">Fix My Website — Starting at $49</a>
</div>

<p style="color:#666;font-size:13px;line-height:1.6;margin-top:30px">
This audit was generated by myAI, an AI-powered business optimization service. No signup was needed and your data is not stored.
</p>
<p style="color:#666;font-size:13px">
Want a more detailed report? Just reply to this email.<br>
Not interested? No problem — reply "stop" and I won't email again.
</p>

</div>

<div style="background:#111;padding:15px 30px;text-align:center;border-top:1px solid #222">
<span style="color:#555;font-size:12px">myAI | info@aoeua.com | <a href="https://aoeua.com/" style="color:#00d4ff;text-decoration:none">aoeua.com</a></span>
</div>

</div>
"""
    return subject, html


def send_audit_email(to_email, to_name, website_url, creds):
    """Run audit on a prospect's site and send them the results."""
    print(f"[OUTREACH] Auditing {website_url} for {to_name}...")

    # Run audit
    report = run_audit(website_url)
    if "error" in report and "overall_score" not in report:
        print(f"[OUTREACH] Audit failed for {website_url}: {report.get('error')}")
        return False

    # Save HTML report
    safe_name = website_url.replace("https://", "").replace("http://", "").replace("/", "_")
    report_path = os.path.join(BASE_DIR, "output", "audits", f"audit_{safe_name}.html")
    generate_html_report(report, report_path)

    # Generate email
    subject, html_body = generate_outreach_email(to_name, website_url, report)

    # Send email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"myAI <{creds['email']}>"
    msg["To"] = to_email
    msg.attach(MIMEText(html_body, "html"))

    try:
        ctx = ssl.create_default_context()
        server = smtplib.SMTP(creds["smtp_host"], creds["smtp_port"], timeout=15)
        server.ehlo()
        server.starttls(context=ctx)
        server.ehlo()
        server.login(creds["email"], creds["password"])
        server.sendmail(creds["email"], to_email, msg.as_string())
        server.quit()

        print(f"[OUTREACH] Sent audit email to {to_email} (Score: {report['overall_score']})")

        # Log
        save_outreach_log({
            "to_email": to_email,
            "to_name": to_name,
            "website": website_url,
            "score": report["overall_score"],
            "grade": report["grade"],
            "issues_count": len(report["seo"]["issues"]),
            "sent_at": datetime.now().isoformat(),
            "status": "sent",
        })
        return True

    except Exception as e:
        print(f"[OUTREACH] Email failed to {to_email}: {e}")
        save_outreach_log({
            "to_email": to_email,
            "to_name": to_name,
            "website": website_url,
            "sent_at": datetime.now().isoformat(),
            "status": "failed",
            "error": str(e),
        })
        return False


def run_outreach_campaign(max_emails=5):
    """Run outreach campaign: audit prospect websites and send results."""
    creds = load_credentials()

    prospects = load_prospects()
    if not prospects:
        print("[OUTREACH] No prospects found. Add prospects to data/prospects.json")
        return

    # Load previous outreach log to avoid re-sending
    log_path = os.path.join(BASE_DIR, "data", "outreach_log.json")
    sent_emails = set()
    if os.path.exists(log_path):
        with open(log_path) as f:
            for entry in json.load(f):
                if entry.get("status") == "sent":
                    sent_emails.add(entry["to_email"])

    sent = 0
    for prospect in prospects:
        if sent >= max_emails:
            break

        email = prospect.get("email", "")
        name = prospect.get("name", prospect.get("business", "there"))
        website = prospect.get("website", "")

        if not email or not website:
            continue
        if email in sent_emails:
            print(f"[OUTREACH] Already emailed {email}, skipping")
            continue

        success = send_audit_email(email, name, website, creds)
        if success:
            sent += 1

    print(f"\n[OUTREACH] Campaign complete: {sent} emails sent out of {max_emails} max")


def get_outreach_stats():
    """Get outreach campaign statistics."""
    log_path = os.path.join(BASE_DIR, "data", "outreach_log.json")
    if not os.path.exists(log_path):
        return {"total": 0, "sent": 0, "failed": 0}

    with open(log_path) as f:
        logs = json.load(f)

    sent = sum(1 for l in logs if l.get("status") == "sent")
    failed = sum(1 for l in logs if l.get("status") == "failed")

    return {
        "total": len(logs),
        "sent": sent,
        "failed": failed,
        "logs": logs,
    }


if __name__ == "__main__":
    max_count = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    run_outreach_campaign(max_emails=max_count)
